---
title: "Апроксимация нейронной сетью"
output:
  html_document: default
  html_notebook: default
  word_document: default
---
####  Using neural network for create regression model CLIs-CRNs
  + <https://yandex.ru/maps/-/CZwvQZpz>

```{r init}
rm(list=ls())
assign("last.warning", NULL, envir = baseenv())
load("crn_table.RData")
```

#### Reading generalized chronologies from the site https://www.ncdc.noaa.gov/paleo/chron_table.html
  + <https://www.ncdc.noaa.gov/paleo/meas_table.html>
  + <ftp://ftp.ncdc.noaa.gov/pub/data/paleo/treering/updates/schweingruber/chronologies/russ055/russ055w_tabs.crn>
  + <ftp://ftp.ncdc.noaa.gov/pub/data/paleo/treering/updates/schweingruber/chronologies/russ055/russ055w_out.txt>
  + <https://s3.amazonaws.com/assets.datacamp.com/img/blog/data+table+cheat+sheet.pdf>
```{r read_rwi_data}
library(reshape2)
library(data.table)
# http://meteo.ru/data/155-meteostations
# 63.23, 125.48   63.95, 124.83  https://yandex.ru/maps/-/CZwvQZpz
DTw <- fread("ftp://ftp.ncdc.noaa.gov/pub/data/paleo/treering/updates/schweingruber/chronologies/russ055/russ055w_tabs.crn")
DTe <- fread("ftp://ftp.ncdc.noaa.gov/pub/data/paleo/treering/updates/schweingruber/chronologies/russ055/russ055e_tabs.crn")
str(DTw)
head(DTw)
DTw[YEAR %in% c(1:5000)]
length(c(min(DTw[,YEAR]): max(DTw[,YEAR]))) == length(DTw[,YEAR])
DTw[, .(YEAR,STD)]
DTw[, plot(YEAR,STD,type="l", col="green")]
DTw[, lines(YEAR,RES,type="l", col="red")]
DTw[, lines(YEAR,ARS,type="l", col="blue")]
```
#### Читаем все обобщенные хронологии на russ
```{r read_all_crn}
str_ex <- "ftp://ftp.ncdc.noaa.gov/pub/data/paleo/treering/updates/schweingruber/chronologies/russ055/russ055w_tabs.crn"
crn_file <- list()
i <- 1
num <- 20
for(num in 20:180){
  if(num > 99){
    crn_file[[i]] <- paste0("ftp://ftp.ncdc.noaa.gov/pub/data/paleo/treering/updates/schweingruber/chronologies/",
                   "russ", num, "/russ", num, "w_tabs.crn")
  } else {
    crn_file[[i]] <- paste0("ftp://ftp.ncdc.noaa.gov/pub/data/paleo/treering/updates/schweingruber/chronologies/",
                   "russ0", num, "/russ0", num, "w_tabs.crn")
  }
  i <- i + 1
}

```
#### Загружаем хронологии в список из data.table
```{r}
library(reshape2)
library(data.table)
crn_table <- list()
for(i in 1:(180-20)){
  if(i == 2  | i == 34 | i == 40 | i == 47 | i == 50) {
    print("next sites")
  }
  else {
    print(i)
    crn_table[[i]] <- fread(as.character(crn_file[i]))
  }
}
```
####
  + <http://www.htmlwidgets.org/>
  + <http://www.htmlwidgets.org/showcase_dygraphs.html>
  + <http://rstudio.github.io/dygraphs/index.html>
  + <http://anonym-mouse.livejournal.com/2323.html>
  

```{r}
# Добавить размеры графика
# считать все серии в список и преобразовать в приложение Shiny
# с выпадающем списком серий
#install.packages("dygraphs")
library(dygraphs)
library(datasets)

dt_w <- DTw[1:(1992-DTw[,min(YEAR)]),]
# http://www.sibran.ru/upload/iblock/407/4078125c856863ff40809cf249876b95.PDF
crn <- structure(c(dt_w[, RES]), .Tsp = c(dt_w[,min(YEAR)], dt_w[,max(YEAR)], 1), class = "ts")
dygraph(crn, main = "Russia, Scotch pine 100  63.23-125.48 1568 1991", ylab = "RWI")  %>% dyRangeSelector(dateWindow = c("1650-01-01","2000-01-01"))

```
###
```{r links}
# http://vs-genn.ru/sites_yakutia/. К
# https://rstudio-pubs-static.s3.amazonaws.com/65323_76ad54e90cd845eab4b7569c81c9d5b0.html
# http://dkhramov.dp.ua/Comp/ShinyLesson01
# http://www.academia.edu/9464470/%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5_%D1%84%D1%80%D0%B5%D0%B9%D0%BC%D0%B2%D0%BE%D1%80%D0%BA%D0%B0_Shiny_%D0%B4%D0%BB%D1%8F_%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8_%D0%B2%D0%B5%D0%B1-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B9_%D0%BD%D0%B0_%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%B5_R
# https://habrahabr.ru/company/microsoft/blog/316032/https://habrahabr.ru/post/253419/
  
  
  


```
